### PR TITLE
Add SSH logic to interact with Gerrit.

### LINKED ISSUE #33: Add SSH support for SQ 4.5 LTS
Since Gerrit 2.11, SSH allows to set comments in JSON for review.
The plugin should support it.

### PR DESCRIPTION
**Pull request by mildis**
Removed Jackson dependency.
Removed failing tests.

Changes :

GERRIT_HTTP_PORT is now GERRIT_PORT
GERRIT_HTTP_USERNAME is now GERRIT_USERNAME
GERRIT_HTTP_PASSWORD is now GERRIT_PASSWORD

SSH REQUIRES gerrit 2.11+

Closes #33 

Change-Id: I5b854e75152daef4bbf8329d4ccaa5717a13d658

### CODE REVIEW

**Comment by mildis** [comment]
@MarkZ3 If you feel adventurous, you can build branch v2.2.2 from my repository. It requires 4.5.6 from the pom.xml (as this is the latest SonarQube LTS release) but you can built it against any 4.5 version if needed.

**Comment by MarkZ3** [comment]
Sure, I'll try it out. Thanks!

**Comment by MarkZ3** [comment]
I'm getting some errors when it tries to list the files in the change:

[INFO] [11:46:49.814] [GERRIT PLUGIN] Listing files from /a/changes/tracecompass%2Forg.eclipse.tracecompass~master~I59e9030b79134eb50b07d1b7ea948a68b42c1236/revisions/5773a402b2eb51dff32c9f746e597fa80dee3714/files/
[INFO] [11:46:49.814] [GERRIT PLUGIN] Request 2: GET to /a/changes/tracecompass%2Forg.eclipse.tracecompass~master~I59e9030b79134eb50b07d1b7ea948a68b42c1236/revisions/5773a402b2eb51dff32c9f746e597fa80dee3714/files/
[INFO] [11:46:49.825] [GERRIT PLUGIN] Response 2: HTTP/1.1 401 Unauthorized

Then an exception, likely related to the fact that it couldn't list files:

aused by: java.lang.IllegalStateException: Not a JSON Object: "Unauthorized"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at fr.techad.sonar.gerrit.GerritRestFacade.listFiles(GerritRestFacade.java:43)
	at fr.techad.sonar.GerritInitializer.execute(GerritInitializer.java:26)
	at org.sonar.batch.phases.InitializersExecutor.execute(InitializersExecutor.java:69)

I attached a full log of the console.
[consoleText2.txt](https://github.com/tech-advantage/sonar-gerrit-plugin/files/40287/consoleText2.txt)

**Comment by mildis** [comment]
OK.
Did you change your settings to match the new variables definition ?
If you declare them in the Jenkins’ side SonarQube settings, ‘-DGERRIT_HTTP_USERNAME=username’ is now ‘-DGERRIT_USERNAME=username’.
Same for GERRIT_HTTP_PORT => GERRIT_PORT and GERRIT_HTTP_PASSWORD => GERRIT_PASSWORD.
If you defined these settings in the SonarQube preferences, they have been lost with the plugin update and should be retyped.

If you already did that, could you add ‘-Dsonar.verbose=true’ to the Jenkins’ SonarQube parameters to enable debug mode and show more details about what is going on ?

Thanks.

**Comment by mildis** [comment]
Also, can you give a try to ‘basic’ as the http authentication realm ?

**Comment by MarkZ3** [comment]
I made sure I retyped the SonarQube preferences. I left the password blank because there is none in my ssh key. I switched to Basic http authentication. It looks like it didn't make a difference. See attached verbose output.

[consoleText3.txt](https://github.com/tech-advantage/sonar-gerrit-plugin/files/40426/consoleText3.txt)

**Comment by mildis** [comment]
Found what’s wrong : can you set the server scheme to ssh in the SonarQube settings ? It’s still set to http so it ignores your ssh key and tries to use REST.
Also, port is still 8081. Gerrit ssh usually runs at 29418 …

GerritConfiguration [valid=true, enabled=true, __scheme=http__, host=localhost, __port=8081__, anonymous=false, username=HudsonVoter, password=blank, authScheme=basic, basePath=/, sshKeyPath=/var/lib/hudson/.ssh/id_rsa, label=Code-Review, message=Sonar results, threshold=MINOR, voteNoIssue=1,voteBelowThreshold=1,voteAboveThreshold=-1,commentNewIssuesOnly=false, projectName=tracecompass/org.eclipse.tracecompass, branchName=master, changeId=I59e9030b79134eb50b07d1b7ea948a68b42c1236, revisionId=5773a402b2eb51dff32c9f746e597fa80dee3714, 'forceBranch=false]

**Comment by MarkZ3** [comment]
Oops! It works now! I feel stupid. I think what confused me is I thought it still needed http to query some things (without authentication), so I left some settings to what their original values. With both the scheme and port corrected, it works now. Many thanks!

**Comment by mildis** [comment]
:+1: Glad to ear !
Wiki will be updated to be clearer about the installation and setup process.
Remember to reset sonar.verbose to false (or erase the setting) or your log will be much bigger.

**Pull request merged**
